DDR4/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('s/', include('Scores.urls', namespace='Scores')),
    path('l/', include('League.urls', namespace='League')),
    path('a/', include('Accounts.urls', namespace='Accounts')),
    path('accounts/', include([
        path('admin/', admin.site.urls, name="access-panel"),
        path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
        path('logout/', auth_views.LogoutView.as_view(next_page='home'), name='logout'),
    ])),
    path('info/', include([
        path('about', views.about, name='about'),
        path('contact', views.contact, name='contact'),
        path('contribute', views.contribute, name='contribute')
    ])),

    # path('feed/', views.FeedSet.as_view(), name='live-feed'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Scores/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

from Scores import views

app_name = 'Scores'
urlpatterns = [
    path('', views.ScoreListing.as_view(), name='score-list'),
    path('detail/<int:pk>', views.ScoreDetail.as_view(), name='score-detail'),
    path('submit', views.ScoreSubmit.as_view(), name='score-submit'),
    path('jsonpretty/', views.JSONView.as_view(), name='json-pretty'),
    path('jsonpretty/<int:pk>', views.JSONDetailView.as_view(), name='json-detail-pretty'),
    path('songDB/', views.SongDB.as_view(), name='dbview'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = format_suffix_patterns(urlpatterns)

Scores/models.py
from django.db import models
from django.urls import reverse

from Accounts.models import Profile


class ChartDifficulty(models.Model):
    difficulty: str = models.CharField(max_length=5)
    step: str = models.CharField(max_length=5)
    shock: str = models.CharField(max_length=5)
    freeze: str = models.CharField(max_length=5)


class ChartLevel(models.Model):
    beginner: ChartDifficulty = models.ForeignKey(ChartDifficulty,
                                                  models.CASCADE,
                                                  related_name="beginner",
                                                  null=True
                                                  )
    basic: ChartDifficulty = models.ForeignKey(ChartDifficulty,
                                               models.CASCADE,
                                               related_name="basic",
                                               null=True
                                               )
    difficult: ChartDifficulty = models.ForeignKey(ChartDifficulty,
                                                   models.CASCADE,
                                                   related_name="difficult",
                                                   null=True
                                                   )
    expert: ChartDifficulty = models.ForeignKey(ChartDifficulty,
                                                models.CASCADE,
                                                related_name="expert",
                                                null=True
                                                )
    challenge: ChartDifficulty = models.ForeignKey(ChartDifficulty,
                                                   models.CASCADE,
                                                   related_name="challenge",
                                                   null=True
                                                   )


class SongChart(models.Model):
    unlock: bool = models.BooleanField(default=False, null=True)
    us_locked: bool = models.BooleanField(default=False, null=True)
    name: str = models.CharField(max_length=100)
    artist: str = models.CharField(max_length=100)
    folder: str = models.CharField(max_length=80, blank=True)
    bpm: str = models.CharField(max_length=20)
    name_translation: str = models.CharField(max_length=100, blank=True)
    artist_translation: str = models.CharField(max_length=100, blank=True)
    genre: str = models.CharField(max_length=50, blank=True)
    single: ChartLevel = models.ForeignKey(ChartLevel, models.CASCADE, related_name="single")
    double: ChartLevel = models.ForeignKey(ChartLevel, models.CASCADE, related_name="double")

    def __str__(self):
        return f"{self.name}"


def user_directory_path(instance, filename):
    """
    Defines the filepath of the user directory
    :param instance:
    :param filename:
    :return:
    """
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return f'images/user_{instance.player.id}/proof_{filename}'


DIFFICULTY_SELECT = (
    ("1", "BEG"),
    ("2", "BSP"),
    ('3', "DSP"),
    ("4", "ESP"),
    ("5", "CSP"),
    ("6", "BDP"),
    ("7", "DDP"),
    ("8", "EDP"),
    ("9", "CDP"),
)


class Score(models.Model):
    song = models.ForeignKey(SongChart, models.CASCADE, related_name='song')
    player = models.ForeignKey(Profile, models.CASCADE, related_name='player')
    difficulty = models.CharField(choices=DIFFICULTY_SELECT, default=1, max_length=1)
    marvelous = models.IntegerField()
    perfect = models.IntegerField()
    great = models.IntegerField()
    good = models.IntegerField()
    OK = models.IntegerField()
    miss = models.IntegerField()
    proof = models.ImageField(upload_to=user_directory_path)
    date = models.DateTimeField(auto_now_add=True)

    def song_list(self, argument):
        """
        Returns the steps of the current song based on the difficulty
        :param argument: usually set to the difficulty of the song chosen
        :return:
        """
        song_type = {
            "BEG": (self.song.single.beginner.step + self.song.single.beginner.freeze) if self.song.single.beginner
            else 0,
            "BSP": (self.song.single.basic.step + self.song.single.basic.freeze) if self.song.single.basic
            else 0,
            "DSP": (self.song.single.difficult.step + self.song.single.difficult.freeze) if
            self.song.single.expert
            else 0,
            "ESP": (self.song.single.expert.step + self.song.single.expert.freeze) if self.song.single.expert
            else 0,
            "CSP": (self.song.single.challenge.step + self.song.single.challenge.freeze) if
            self.song.single.challenge
            else 0,
            "BDP": (self.song.double.basic.step + self.song.double.basic.freeze) if self.song.double.basic
            else 0,
            "DDP": (self.song.double.difficult.step + self.song.double.difficult.freeze) if
            self.song.double.difficult
            else 0,
            "EDP": (self.song.double.expert.step + self.song.double.expert.freeze) if self.song.double.expert
            else 0,
            "CDP": (self.song.double.challenge.step + self.song.double.challenge.freeze) if
            self.song.double.challenge
            else 0,
        }
        return song_type.get(argument, 0)

    @property
    def ex_check(self):
        """
        Checks the EX score of a song to validate the score having correct steps/jumps/shocks
        :return:
        """
        tip = self.difficulty
        steps = Score.song_list(self, tip)

        num_steps = (self.marvelous + self.perfect + self.great + self.good + self.OK + self.miss)
        return True if num_steps == steps else False

    @property
    def ex(self):
        """
        Returns the EX score for the song.
        :return:
        """
        score = (self.marvelous * 3) + (self.perfect * 2) + (self.great * 1) + (self.OK * 3)
        return score

    @property
    def full_score(self):
        """
        Returns the full number score of the song
        :return:
        """
        tip = self.difficulty
        steps = Score.song_list(self, tip)

        if (steps + self.OK) == 0:
            return None
        else:
            num_steps = self.marvelous + self.perfect + self.great + self.good + self.miss
            marv_score = 1000000 / (steps + self.OK)
            perf_score = marv_score - 10
            great_score = (marv_score * 0.6) - 10
            good_score = (marv_score * 0.2) - 10
            reg_score = ((marv_score * (self.marvelous + self.OK) + (perf_score * self.perfect) + (
                    great_score * self.great) + (
                                  good_score * self.good) + 0.1) / 10) * 10
            if num_steps != 0:
                return round(reg_score)

    @property
    def full_combo(self):
        """
        Shows the special text for full combos.
        :return:
        """
        if self.miss == 0:
            if self.good == 0:
                if self.great == 0:
                    if self.perfect == 0:
                        if self.marvelous == 0:
                            pass
                        else:
                            return "You are Supreme!"
                    else:
                        return "Yellow [Perfect Full Combo]"
                else:
                    return "Green [Great Full Combo]"
            else:
                return "Blue [Good Full Combo]"
        else:
            return False

    @property
    def letter_grade(self):
        """
        Returns a letter grade for the song
        :return:
        """
        if self.full_score is int:
            if self.full_score >= 990000:
                return "AAA"
            if 950000 <= self.full_score <= 989990:
                return "AA+"
            if 900000 <= self.full_score <= 949990:
                return "AA"
            if 890000 <= self.full_score <= 899990:
                return "AA-"
            if 850000 <= self.full_score <= 889990:
                return "A+"
            if 800000 <= self.full_score <= 849990:
                return "A"
            if 790000 <= self.full_score <= 799990:
                return "A-"
            if 750000 <= self.full_score <= 789990:
                return "B+"
            if 700000 <= self.full_score <= 749990:
                return "B"
            if 690000 <= self.full_score <= 699990:
                return "B-"
            if 650000 <= self.full_score <= 689990:
                return "C+"
            if 600000 <= self.full_score <= 649990:
                return "C"
            if 590000 <= self.full_score <= 599990:
                return "C-"
            if 550000 <= self.full_score <= 589990:
                return "D+"
            if 0 <= self.full_score <= 549990:
                return "D / E"
        elif self.full_score is None:
            return "NG"
        else:
            return "N/A"

    def get_absolute_url(self):
        return reverse('Scores:score-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return f"{self.song}, {self.player}"

Scores/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column, Submit
from django import forms

from Scores.models import Score


class ScoreForm(forms.ModelForm):
    class Meta:
        model = Score
        exclude = ('player', 'date',)
        help_texts = {
            'proof': "We need you to show off your swag, mate.",
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.layout = Layout(
            Row(
                Column('marvelous', css_class='form-group col-md-2'),
                Column('perfect', css_class='form-group col-md-2'),
                Column('great', css_class='form-group col-md-2'),
                Column('good', css_class='form-group col-md-2'),
                Column('OK', css_class='form-group col-md-2'),
                Column('miss', css_class='form-group col-md-2'),
            ),
            Row(
                Column('song', css_class='form-group col-md-10', css_id='song_title'),
                Column('difficulty', css_class='form-group col-md-2'),
            ),
            'proof',
            Submit('Submit', 'Send Up', css_class='btn btn-block btn-outline-light'),
        )

Scores/views.py
from django.urls import reverse_lazy
from django.views import generic
from rest_framework import generics

from Scores.forms import ScoreForm
from Scores.models import Score, SongChart
from Scores.serializers import SongChartSerializer


class ScoreListing(generic.ListView):
    model = Score
    queryset = Score.objects.order_by('date').all()
    template_name = "scores/score-list-all.html"


class ScoreDetail(generic.DetailView):
    model = Score
    queryset = Score.objects.all()
    template_name = "scores/score-detail.html"


class ScoreSubmit(generic.CreateView):
    model = Score
    form_class = ScoreForm
    queryset = Score.objects.order_by('song__name').all()
    template_name = "scores/score-submit.html"
    success_url = reverse_lazy('Scores:score-list')
    success_message = "Score submitted!"

    def form_valid(self, form):
        form.instance.player = self.request.user.profile
        return super().form_valid(form)


class SongDB(generic.ListView):
    model = SongChart
    queryset = SongChart.objects.all()
    template_name = "scores/score-song-list.html"


class JSONView(generics.ListAPIView):
    queryset = SongChart.objects.all()
    serializer_class = SongChartSerializer


class JSONDetailView(generics.RetrieveAPIView):
    queryset = SongChart.objects.all()
    serializer_class = SongChartSerializer

templates/scores/score-detail.html
{% extends 'base.html' %}

{% block title %}
    Score Detail for {{ score.player.user }} - {{ score.song }}
{% endblock %}
{% block page-title %}
    Score Detail
{% endblock %}
{% block page-sub-title %}
    {{ score.player.user }} - {{ score.song }} [{{ score.get_difficulty_display }}]
{% endblock %}
{% block content %}
    <div class="row mx-auto">
        <div class="col-sm-6 rounded p-2">
            <table class="table table-striped table-dark table-bordered text-center">
                <thead class="thead-light">
                <tr>
                    <th colspan="2"><h3>Play Details for {{ score.date|date }}</h3></th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>
                        Player
                    </td>
                    <td>
                        {{ score.player.user.username }}
                    </td>
                </tr>
                <tr>
                    <td>Score</td>
                    <td>{{ score.full_score }}</td>
                </tr>
                <tr>
                    <td>Score Rank</td>
                    <td><b>{{ score.letter_grade }}</b></td>
                </tr>
                <tr>
                    <td colspan="2">
                        <img src="{{ score.proof.url }}" alt="Score proof" class="img-thumbnail">
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="col-sm-6 rounded p-2">
            <table class="table table-striped table-dark table-bordered text-center">
                <thead class="thead-light">
                <tr>
                    <th colspan="2">
                        <h3>Score Breakdown</h3>
                    </th>
                </tr>
                </thead>
                <tbody>
                {% if score.full_combo %}
                    <tr>
                        {% if score.full_score is None %}
                            <td colspan="2" class="text-danger">We believe this score is incorrect, possibly fake.
                                Please check your numbers because that seems impossible.
                            </td>
                        {% elif score.ex_check is False %}
                            <td colspan="2" class="text-danger">UNDER REVIEW</td>
                        {% else %}
                            <td colspan="2">{{ score.full_combo }}</td>
                        {% endif %}
                    </tr>
                {% endif %}
                <tr>
                    <td><b>EX SCORE</b></td>
                    <td>{{ score.ex }}</td>
                </tr>
                <tr>
                    <td>Marvelous</td>
                    <td>{{ score.marvelous }}</td>
                </tr>
                <tr>
                    <td>Perfect</td>
                    <td>{{ score.perfect }}</td>
                </tr>
                <tr>
                    <td>Great</td>
                    <td>{{ score.great }}</td>
                </tr>
                <tr>
                    <td>Good</td>
                    <td>{{ score.good }}</td>
                </tr>
                <tr>
                    <td>OK</td>
                    <td>{{ score.OK }}</td>
                </tr>
                <tr>
                    <td>Miss</td>
                    <td>{{ score.miss }}</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/scores/score-list-all.html
{% extends 'base.html' %}
{% block title %}
    Score Listing
{% endblock %}
{% block page-title %}
    Scores!
{% endblock %}
{% block page-sub-title %}
    The latest scores from the network!
{% endblock %}
{% block content %}
    {% if score_list.count > 0 %}
        <div class="row text-center">
            <div class="col-md mx-auto">
                <h2 class="border my-0">Latest Scores</h2>
                <table class="table table-sm table-striped table-dark table-bordered" id="latest_scores">
                    <thead class="thead-light">
                    <tr>
                        <th scope="col">Player</th>
                        <th scope="col">Song</th>
                        <th scope="col">Score</th>
                        <th scope="col"></th>
                    </tr>
                    </thead>
                    <tbody class="">
                    {% for score in score_list|slice:":10" %}
                        <tr class="">
                            <td>{{ score.player.user.username }}</td>
                            <td>{{ score.song }}</td>
                            <td>{{ score.ex }}</td>
                            <td><a href="{% url 'Scores:score-detail' score.pk %}"
                                   class="btn btn-sm btn-primary btn-block">Check</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            {% if user.is_authenticated %}
                <div class="col-md-6 mx-auto"><h2 class="border my-0">Your scores</h2>
                    <table class="table table-sm table-striped table-dark table-bordered" id="user_scores">
                        <thead class="thead-light">
                        <tr>
                            <th scope="col">Song</th>
                            <th scope="col">Score</th>
                            <th scope="col"></th>
                        </tr>
                        </thead>
                        <tbody class="">
                        {% for score in score_list %}
                            {% if score.player.user == user %}
                                <tr class="">
                                    <td>{{ score.song }}</td>
                                    <td>{{ score.ex }}</td>
                                    <td><a href="{% url 'Scores:score-detail' score.pk %}"
                                           class="btn btn-sm btn-primary btn-block">Check</a>
                                    </td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% endif %}
        </div>
    {% else %}
        <h4 class="text-center">No scores are loaded.</h4>
    {% endif %}
{% endblock %}

templates/scores/score-submit.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Score Submission
{% endblock %}
{% block page-title %}
    Score Submission
{% endblock %}
{% block page-sub-title %}
    This is it, your chance to prove yourself. Keep in mind that your score must be accurate down to the step count
    otherwise it won't count until further review.
{% endblock %}

{% block content %}
    {% crispy form %}
{% endblock %}

templates/scores/song_db.html
{% extends base.html %}

{% block title %}
    Song DB
{% endblock %}
{% block content %}
    {% if song_list %}
        <table>
        <thead class="thead-light">
        <tr>
        <th>Name</th>
        <th>Artist</th>
        <th>BPM</th>
        <th>Beginner</th>
        <th>Basic</th>
        <th>Difficult</th>
        <th>Expert</th>
        <th>Challenge</th>
        </thead>
        </tr>
        {% for song in song_list %}
                 <tr>
                    <td>{{ song.name }}</td>
                 <td>{{ song.artist }}</td>
                 <td>{{ song.bpm }}</td>
                 <td>{{ song.beg_step_count }}</td>
                 <td>{{ song.bsp_step_count }}</td>
                 <td>{{ song.dsp_step_count }}</td>
                 <td>{{ song.esp_step_count }}</td>
                 </tr>
        {% endfor %}
        </table>
    {% endif %}
{% endblock %}