Accounts/urls.py
from django.contrib import admin
from django.urls import path, include

from Accounts import views

app_name = "Accounts"
urlpatterns = [
    path('admin/', admin.site.urls, name='single_akumu_shinjen'),
    path('update_profile', views.update_profile, name='update-profile'),
    path('register', views.register, name='register'),
    path('', include([
        path('', views.ProfileListing.as_view(), name='profile-list'),
        path('view/<int:pk>', views.ProfileView.as_view(), name='view-profile'),
        path('follow/<int:pk>', views.follower_add, name='follow'),
        path('unfollow/<int:pk>', views.follower_delete, name='unfollow'),
    ])),
]
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

DDR4/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('s/', include('Scores.urls', namespace='Scores')),
    path('l/', include('League.urls', namespace='League')),
    path('a/', include('Accounts.urls', namespace='Accounts')),
    path('accounts/', include([
        path('admin/', admin.site.urls, name="access-panel"),
        path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
        path('logout/', auth_views.LogoutView.as_view(next_page='home'), name='logout'),
    ])),
    path('info/', include([
        path('about', views.about, name='about'),
        path('contact', views.contact, name='contact'),
        path('contribute', views.contribute, name='contribute')
    ])),

    # path('feed/', views.FeedSet.as_view(), name='live-feed'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

League/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from League import views

app_name = "League"
urlpatterns = [
    path('l/', include([
        path('', views.LeagueViewAll.as_view(), name='league-list'),
        path('MakeLeague', views.LeagueCreate.as_view(), name='league-add'),
        path('<int:pk>', views.LeagueView.as_view(), name='league-view'),
        path('<int:pk>/league_entry', views.enter_league, name='league-entry')
    ])),
    path('t/', include([
        path('', views.TrialViewAll.as_view(), name='trial-list'),
        path('<int:pk>', views.TrialView.as_view(), name='trial-view'),
        path('<int:pk>/trial_entry', views.add_trial, name='trial-entry'),
    ])),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Scores/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

from Scores import views

app_name = 'Scores'
urlpatterns = [
    path('', views.ScoreListing.as_view(), name='score-list'),
    path('detail/<int:pk>', views.ScoreDetail.as_view(), name='score-detail'),
    path('submit', views.ScoreSubmit.as_view(), name='score-submit'),
    path('jsonpretty/', views.JSONView.as_view(), name='json-pretty'),
    path('jsonpretty/<int:pk>', views.JSONDetailView.as_view(), name='json-detail-pretty'),
    path('songDB/', views.SongDB.as_view(), name='dbview'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = format_suffix_patterns(urlpatterns)

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %} - 4rrowstomp</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark shadow py-0">
    <h2><a class="navbar-brand" href="{% url 'home' %}">4RROWSMASH</a></h2>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-between" id="navbarNavDropdown">
        <ul class="navbar-nav py-0">
            {% if user.is_authenticated %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'League:league-list' %}">League</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'League:trial-list' %}">Trial</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'Scores:score-list' %}">Scores <span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'Accounts:profile-list' %}">Players</a>
                </li>
            {% else %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'about' %}">About</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'contact' %}">Contact</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'contribute' %}">Contribute</a>
                </li>
            {% endif %}
        </ul>
        <ul class="navbar-nav justify-content-end">
            {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ user.username }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                        {% if user.is_superuser %}
                            <h5 class="dropdown-header">Admin</h5>
                            <a class="dropdown-item" href="http://127.0.0.1:8000/admin/">Access Panel</a>
                            <hr/>
                        {% endif %}
                        <h5 class="dropdown-header">Simple Menu</h5>
                        <a class="dropdown-item" href="{% url 'Accounts:view-profile' user.profile.pk %}">View
                            Profile</a>
                        <a class="dropdown-item" href="{% url 'Accounts:update-profile' %}">Update Profile</a>
                        <hr>
                        <h5 class="dropdown-header">Scores</h5>
                        <a class="dropdown-item" href="{% url 'Scores:score-submit' %}">Submit Score</a>
                        <hr>
                        <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                    </div>
                </li>
            {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Login</a></li>
                <li class="nav-item"><a class="nav-link" href="#">|</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'Accounts:register' %}">Register</a></li>
            {% endif %}
        </ul>
    </div>
</nav>
<header id="banner" class="text-center">
    {% block header %}

    {% endblock %}
    <div class="text-center py-3 shadow bg-secondary text-light">
        <h2>{% block page-title %}{% endblock %}</h2>
        <h5 class="pb-4">{% block page-sub-title %}{% endblock %}</h5>
    </div>
</header>
{% if messages %}
    {% for message in messages %}
        <div class="alert fade show alert-dismissable alert-{% if message.tags %}{{ message.tags }}"{% endif %}
             role="alert">{{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                    aria-hidden="true">&times;</span></button>
        </div>
    {% endfor %}
{% endif %}
<div class="container py-4">
    {% block content %}{% endblock %}
    <hr/>
    <div class="text-center py-5 jumbotron text-dark">
        <h4 class="display-3">Pre-&alpha; [v.0.1]</h4>
        <h5>This is not even fully conceptualized it's so alpha.</h5>
        <p>Everything here is still in the building stages, from the profiles to the score tracking to the freaking
            ranking system.
            I really want to make sure that everything is fully sketched out and planned so that beginners and pros can
            jump in without worry about where they are or should be.
            Dance Dance Revolution is - first and foremost - a rhythm game with the emphasis on GAME. You should have
            fun, mate!</p>
    </div>
</div>
<footer class="text-center py-2 bg-dark text-light">
    <div class="row container-fluid mx-auto">
        <div class="col-sm mx-auto align-middle text-md-left">Project Arrowstomp</div>
        <div>{% block footer %}{% endblock %}</div>
        <div class="col-sm mx-auto align-middle text-md-right">2018 [-] Phantom Hex</div>
    </div>
</footer>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block title %}
    Arrowsmash
{% endblock %}

{% block header %}
    <img src="https://wallpapers.wallhaven.cc/wallpapers/full/wallhaven-718566.jpg" alt="banner">
{% endblock %}
{% block content %}
    <div class="jumbotron text-center text-dark">
        <h1 class="display-1">Project Arrowsmash</h1>
        {% if user.is_authenticated %}
            {% if user.first_name %}
                Welcome back, {{ user.first_name }}!
                <br/>
            {% endif %}
        {% endif %}
    </div>
    <section>
        <div>This is a project made for players of Dance Dance Revolution. Currently, this one only services players of
            the latest version. I will be adding more versions over time.
        </div>
        <hr/>
    </section>
    <section>
        {% lorem 6 p random %}
    </section>
{% endblock %}
{% block footer %}
    {% if user.is_authenticated %}
        <small>Last login: {{ user.last_login }}</small>{% endif %}
{% endblock %}