Accounts/urls.py
from django.contrib import admin
from django.urls import path, include

from Accounts import views

app_name = "Accounts"
urlpatterns = [
    path('admin/', admin.site.urls, name='single_akumu_shinjen'),
    path('update_profile', views.update_profile, name='update-profile'),
    path('register', views.register, name='register'),
    path('', include([
        path('', views.ProfileListing.as_view(), name='profile-list'),
        path('view/<int:pk>', views.ProfileView.as_view(), name='view-profile'),
        path('follow/<int:pk>', views.follower_add, name='follow'),
        path('unfollow/<int:pk>', views.follower_delete, name='unfollow'),
    ])),
]
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

DDR4/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('s/', include('Scores.urls', namespace='Scores')),
    path('l/', include('League.urls', namespace='League')),
    path('a/', include('Accounts.urls', namespace='Accounts')),
    path('accounts/', include([
        path('admin/', admin.site.urls, name="access-panel"),
        path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
        path('logout/', auth_views.LogoutView.as_view(next_page='home'), name='logout'),
    ])),
    path('info/', include([
        path('about', views.about, name='about'),
        path('contact', views.contact, name='contact'),
        path('contribute', views.contribute, name='contribute')
    ])),

    # path('feed/', views.FeedSet.as_view(), name='live-feed'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

League/models.py
from datetime import datetime, date
from typing import Tuple

from django.contrib.auth.models import User
from django.db import models
from django.db.models.fields.files import ImageFieldFile

from Accounts.models import Profile
from Scores.models import SongChart

DIVISION_CHOICES = [
    ('M', 'Master'),
    ('U', 'Upper Expert'),
    ('L', 'Lower Expert'),
    ('N', 'Novice')
]


class LeagueManager(models.Manager):
    """League manager"""

    @staticmethod
    def enter_league(event, entry, div=None):
        """Enters someone into a League
        :param event: The League in question
        :param entry: The user entered into it
        :param div: The division as an int?
        :return:
        """
        if div is None:
            div = 2
        rel = LeagueEntry.objects.get_or_create(tourney=event, entrants=entry, division=div)
        return rel

    def __str__(self):
        return F"{self.tourney.name} - {self.entrants.rival_code} - {self.division}"


class League(models.Model):
    """Model for the Leagues"""
    name: str = models.CharField(max_length=100)
    organizer: User = models.OneToOneField(User, on_delete=models.CASCADE)
    rules: str = models.TextField(max_length=10000, help_text="Detail all of the rules of your League here.")
    competition_date_start: date = models.DateField(default=datetime.now)
    competition_date_end: date = models.DateField(default=datetime.now)

    @property
    def __str__(self):
        return f"{self.name}, {self.competition_date_start} - {self.competition_date_end}"


class LeagueResult(models.Model):
    """Model for league results display"""
    league: League = models.ForeignKey(League, models.CASCADE)
    winner: Profile = models.ForeignKey(Profile, on_delete=models.DO_NOTHING, related_name='winner')
    second: Profile = models.ForeignKey(Profile, on_delete=models.DO_NOTHING, related_name='second_place')
    third: Profile = models.ForeignKey(Profile, on_delete=models.DO_NOTHING, related_name='third_place')

    @property
    def __str__(self):
        return f"{self.league.name}"


class LeagueEntry(models.Model):
    """Model for league entry results"""
    league: League = models.ForeignKey(League, models.CASCADE)
    entrants: Profile = models.ForeignKey(Profile, on_delete=models.DO_NOTHING, related_name='entrant')
    division: str = models.CharField(choices=DIVISION_CHOICES, max_length=1)

    federation: LeagueManager = LeagueManager()


class TrialManager(models.Manager):
    """Trial management"""

    @staticmethod
    def start_trial(event, dancer):
        """
        For adding a trial.
        :param event: Trial itself.
        :param dancer: The profile of the player taking it on.
        :return:
        """
        rel: Tuple[TrialEntry, bool] = TrialEntry.objects.get_or_create(trial=event, player=dancer)
        return rel


class Trial(models.Model):
    """Model for Trials"""
    title: str = models.CharField(max_length=100)
    deadline: datetime = models.DateTimeField()
    division: str = models.CharField(choices=DIVISION_CHOICES, max_length=1)
    song1: SongChart = models.ForeignKey(SongChart, models.CASCADE, related_name="first_song")
    song2: SongChart = models.ForeignKey(SongChart, models.CASCADE, related_name="second_song")
    song3: SongChart = models.ForeignKey(SongChart, models.CASCADE, related_name="third_song")
    song4: SongChart = models.ForeignKey(SongChart, models.CASCADE, related_name="final_song")
    art: ImageFieldFile = models.ImageField(null=True, blank=True, upload_to='images/trial_art')

    def __str__(self):
        return f"{self.title} - {self.deadline}"

    @property
    def trial_list(self):
        """
        Returns a list name for the trials.
        :return:
        """
        return f"{self.song1.name}, {self.song2.name}, {self.song3.name}, {self.song4.name}"


class TrialEntry(models.Model):
    """Model for trial entry"""
    trial: Trial = models.ForeignKey(Trial, models.CASCADE, related_name="challenge")
    player: Profile = models.ForeignKey(Profile, models.CASCADE, related_name="challenger")

    objects: TrialManager = TrialManager()

Scores/models.py
from django.db import models
from django.urls import reverse

from Accounts.models import Profile


class ChartDifficulty(models.Model):
    difficulty: str = models.CharField(max_length=5)
    step: str = models.CharField(max_length=5)
    shock: str = models.CharField(max_length=5)
    freeze: str = models.CharField(max_length=5)


class ChartLevel(models.Model):
    beginner: ChartDifficulty = models.ForeignKey(ChartDifficulty,
                                                  models.CASCADE,
                                                  related_name="beginner",
                                                  null=True
                                                  )
    basic: ChartDifficulty = models.ForeignKey(ChartDifficulty,
                                               models.CASCADE,
                                               related_name="basic",
                                               null=True
                                               )
    difficult: ChartDifficulty = models.ForeignKey(ChartDifficulty,
                                                   models.CASCADE,
                                                   related_name="difficult",
                                                   null=True
                                                   )
    expert: ChartDifficulty = models.ForeignKey(ChartDifficulty,
                                                models.CASCADE,
                                                related_name="expert",
                                                null=True
                                                )
    challenge: ChartDifficulty = models.ForeignKey(ChartDifficulty,
                                                   models.CASCADE,
                                                   related_name="challenge",
                                                   null=True
                                                   )


class SongChart(models.Model):
    unlock: bool = models.BooleanField(default=False, null=True)
    us_locked: bool = models.BooleanField(default=False, null=True)
    name: str = models.CharField(max_length=100)
    artist: str = models.CharField(max_length=100)
    folder: str = models.CharField(max_length=80, blank=True)
    bpm: str = models.CharField(max_length=20)
    name_translation: str = models.CharField(max_length=100, blank=True)
    artist_translation: str = models.CharField(max_length=100, blank=True)
    genre: str = models.CharField(max_length=50, blank=True)
    single: ChartLevel = models.ForeignKey(ChartLevel, models.CASCADE, related_name="single")
    double: ChartLevel = models.ForeignKey(ChartLevel, models.CASCADE, related_name="double")

    def __str__(self):
        return f"{self.name}"


def user_directory_path(instance, filename):
    """
    Defines the filepath of the user directory
    :param instance:
    :param filename:
    :return:
    """
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return f'images/user_{instance.player.id}/proof_{filename}'


DIFFICULTY_SELECT = (
    ("1", "BEG"),
    ("2", "BSP"),
    ('3', "DSP"),
    ("4", "ESP"),
    ("5", "CSP"),
    ("6", "BDP"),
    ("7", "DDP"),
    ("8", "EDP"),
    ("9", "CDP"),
)


class Score(models.Model):
    song = models.ForeignKey(SongChart, models.CASCADE, related_name='song')
    player = models.ForeignKey(Profile, models.CASCADE, related_name='player')
    difficulty = models.CharField(choices=DIFFICULTY_SELECT, default=1, max_length=1)
    marvelous = models.IntegerField()
    perfect = models.IntegerField()
    great = models.IntegerField()
    good = models.IntegerField()
    OK = models.IntegerField()
    miss = models.IntegerField()
    proof = models.ImageField(upload_to=user_directory_path)
    date = models.DateTimeField(auto_now_add=True)

    def song_list(self, argument):
        """
        Returns the steps of the current song based on the difficulty
        :param argument: usually set to the difficulty of the song chosen
        :return:
        """
        song_type = {
            "BEG": (self.song.single.beginner.step + self.song.single.beginner.freeze) if self.song.single.beginner
            else 0,
            "BSP": (self.song.single.basic.step + self.song.single.basic.freeze) if self.song.single.basic
            else 0,
            "DSP": (self.song.single.difficult.step + self.song.single.difficult.freeze) if
            self.song.single.expert
            else 0,
            "ESP": (self.song.single.expert.step + self.song.single.expert.freeze) if self.song.single.expert
            else 0,
            "CSP": (self.song.single.challenge.step + self.song.single.challenge.freeze) if
            self.song.single.challenge
            else 0,
            "BDP": (self.song.double.basic.step + self.song.double.basic.freeze) if self.song.double.basic
            else 0,
            "DDP": (self.song.double.difficult.step + self.song.double.difficult.freeze) if
            self.song.double.difficult
            else 0,
            "EDP": (self.song.double.expert.step + self.song.double.expert.freeze) if self.song.double.expert
            else 0,
            "CDP": (self.song.double.challenge.step + self.song.double.challenge.freeze) if
            self.song.double.challenge
            else 0,
        }
        return song_type.get(argument, 0)

    @property
    def ex_check(self):
        """
        Checks the EX score of a song to validate the score having correct steps/jumps/shocks
        :return:
        """
        tip = self.difficulty
        steps = Score.song_list(self, tip)

        num_steps = (self.marvelous + self.perfect + self.great + self.good + self.OK + self.miss)
        return True if num_steps == steps else False

    @property
    def ex(self):
        """
        Returns the EX score for the song.
        :return:
        """
        score = (self.marvelous * 3) + (self.perfect * 2) + (self.great * 1) + (self.OK * 3)
        return score

    @property
    def full_score(self):
        """
        Returns the full number score of the song
        :return:
        """
        tip = self.difficulty
        steps = Score.song_list(self, tip)

        if (steps + self.OK) == 0:
            return None
        else:
            num_steps = self.marvelous + self.perfect + self.great + self.good + self.miss
            marv_score = 1000000 / (steps + self.OK)
            perf_score = marv_score - 10
            great_score = (marv_score * 0.6) - 10
            good_score = (marv_score * 0.2) - 10
            reg_score = ((marv_score * (self.marvelous + self.OK) + (perf_score * self.perfect) + (
                    great_score * self.great) + (
                                  good_score * self.good) + 0.1) / 10) * 10
            if num_steps != 0:
                return round(reg_score)

    @property
    def full_combo(self):
        """
        Shows the special text for full combos.
        :return:
        """
        if self.miss == 0:
            if self.good == 0:
                if self.great == 0:
                    if self.perfect == 0:
                        if self.marvelous == 0:
                            pass
                        else:
                            return "You are Supreme!"
                    else:
                        return "Yellow [Perfect Full Combo]"
                else:
                    return "Green [Great Full Combo]"
            else:
                return "Blue [Good Full Combo]"
        else:
            return False

    @property
    def letter_grade(self):
        """
        Returns a letter grade for the song
        :return:
        """
        if self.full_score is int:
            if self.full_score >= 990000:
                return "AAA"
            if 950000 <= self.full_score <= 989990:
                return "AA+"
            if 900000 <= self.full_score <= 949990:
                return "AA"
            if 890000 <= self.full_score <= 899990:
                return "AA-"
            if 850000 <= self.full_score <= 889990:
                return "A+"
            if 800000 <= self.full_score <= 849990:
                return "A"
            if 790000 <= self.full_score <= 799990:
                return "A-"
            if 750000 <= self.full_score <= 789990:
                return "B+"
            if 700000 <= self.full_score <= 749990:
                return "B"
            if 690000 <= self.full_score <= 699990:
                return "B-"
            if 650000 <= self.full_score <= 689990:
                return "C+"
            if 600000 <= self.full_score <= 649990:
                return "C"
            if 590000 <= self.full_score <= 599990:
                return "C-"
            if 550000 <= self.full_score <= 589990:
                return "D+"
            if 0 <= self.full_score <= 549990:
                return "D / E"
        elif self.full_score is None:
            return "NG"
        else:
            return "N/A"

    def get_absolute_url(self):
        return reverse('Scores:score-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return f"{self.song}, {self.player}"

templates/profiles/profile-update.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Update Profile
{% endblock %}
{% block page-title %}
    Update Profile
{% endblock %}
{% block page-sub-title %}
    Change it up!
{% endblock %}
{% block content %}
    <h2 class="text-center border rounded">Basic Information</h2>
    <form method="post" action="{% url 'Accounts:update-profile' %}" enctype="multipart/form-data" novalidate>
        {% crispy user_form %}
        <hr/>
        <h2 class="text-center border rounded">Additional information</h2>
        {% crispy profile_form %}
        <hr/>
        <button type="submit" class="btn btn-primary btn-block">Edit</button>
    </form>
    <hr/>

{% endblock %}

templates/profiles/profile-view.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}
    Profile View
{% endblock %}
{% block page-title %}
    <h2 class="mb-1">{{ profile.user.username }}</h2>
{% endblock %}
{% block page-sub-title %}
    <p class="text-right border-top bg-primary p-1">
        <small>{{ profile.age }} | {{ profile.get_gender_display }}
            | {{ profile.score_set.count }} score{{ profile.score_set.count|pluralize }} </small>
    </p>
{% endblock %}

{% block content %}
    <section class="row mx-auto py-4 border rounded bg-secondary">
        <div class="col-sm-4" id="avatar_container">
            <img src="{{ profile.avatar.url }}" alt="AVATAR" class="img-thumbnail img-circle-avatar text-center shadow">
            <br/>
        </div>
        <div class="col-sm-8" id="information_container">
            <table class="table table-sm table-dark shadow-lg table-bordered">
                <thead class="thead-light text-center">
                <tr>
                    <th colspan="2"><b>Personal Stats</b></th>
                </tr>
                </thead>
                <tbody>
                {% if profile.user.first_name and profile.user.last_name %}
                    <tr>
                        <td><b>Name</b></td>
                        <td>{{ profile.user.get_full_name }}</td>
                    </tr>{% endif %}
                {% if profile.city and profile.state %}
                    <tr>
                        <td><b>Location</b></td>
                        <td>{{ profile.city }}, {{ profile.state }}</td>
                    </tr>
                {% endif %}
                {% if profile.rival_code %}
                    <tr>
                        <td><b>Rival Code</b></td>
                        <td>{{ profile.rival_code }}</td>
                    </tr>
                {% endif %}
                {% if profile.tagline %}
                    <tr>
                        <td colspan="2" class="text-center">"{{ profile.tagline }}"</td>
                    </tr>
                {% endif %}
                {% if profile.stalked.count > 0 %}
                    <tr>
                        <td colspan="2" class="text-center">{{ profile.stalked.count }}
                            follower{{ profile.stalked.count|pluralize }}</td>
                    </tr>
                {% endif %}
                </tbody>
            </table>
            {% if user.is_authenticated %}
                {% if user.profile == profile %}
                {% elif profile.stalked.get not in user.profile.stalker.all %}
                    <div>
                        <form method="post" action="{% url 'Accounts:follow' profile.pk %}">
                            {% csrf_token %}
                            <button class="btn btn-dark btn-block">Follow them</button>
                        </form>
                    </div>
                {% else %}
                    <div>
                        <form method="post" action="{% url 'Accounts:unfollow' profile.pk %}">
                            {% csrf_token %}
                            <button class="btn btn-outline-dark btn-block">Unfollow them</button>
                        </form>
                    </div>
                {% endif %}
            {% endif %}
        </div>
        <hr/>
    </section>
    <footer class="text-center py-4">
        {% if profile.bio %}
            <h3 class="border">Personal Bio</h3>
            <p>{{ profile.bio }}</p>
            <hr/>
        {% endif %}
    </footer>
    <div class="text-center row">
        {% if profile.score_set.count > 0 %}
            <div class="col-sm-6" id="latest_score">
                <h3 class="border mb-0">Latest Scores</h3>
                <table class="table table-sm table-striped table-dark table-bordered">
                    <thead class="thead-light">
                    <tr>
                        <th scope="col">Date</th>
                        <th scope="col">Song</th>
                        <th scope="col">Rank</th>
                        <th scope="col">EX</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for score in profile.score_set.all %}
                        <tr>
                            <td>{{ score.date|date }}</td>
                            <td>{{ score.song.name }}</td>
                            <td>{{ score.letter_grade }}</td>
                            <td>{{ score.ex }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <hr/>
            </div>
        {% endif %}
        {% if profile.user.league.leagueentry_set %}
            <div class="text-center col-sm-6" id="leagues_entered">
                {% if profile.user.league.leagueentry_set.count > 0 %}
                    <h3 class="border mb-0">Leagues Entered</h3>
                    <table class="table table-striped table-dark table-bordered">
                        <thead class="thead-light">
                        <tr>
                            <th colspan="2">Leagues</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for entry in profile.user.league.leagueentry_set.all %}
                            {% if entry.trial.deadline %}
                            {% else %}
                                <tr>
                                    <td>{{ entry.trial.name }}</td>
                                    <td>{{ entry.trial.tourney_date }}</td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                        </tbody>
                    </table>
                {% endif %}
            </div>
        {% endif %}

        {% if profile.winner.count > 0 or profile.second_place.count > 0 or profile.third_place.count > 0 %}
            <div class="col-sm-6" id="league_placement">
                <h3 class="border mb-0">Leagues Placed</h3>
                <table class="table table-striped table-dark table-bordered">
                    <thead class="thead-light">
                    <tr>
                        <th scope="col">Placement</th>
                        <th scope="col">League</th>
                        <th scope="col">Date</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% if profile.winner.count > 0 %}
                        {% for tourney in profile.winner.all %}
                            <tr>
                                <td>Winner!</td>
                                <td>{{ tourney.tourney }}</td>
                                <td>{{ tourney.tourney.Date }}</td>
                            </tr>
                        {% endfor %}
                    {% elif profile.second_place.count > 0 %}
                        {% for tourney in profile.second_place.all %}
                            <tr>
                                <td>2nd</td>
                                <td>{{ tourney.tourney }}</td>
                                <td>{{ tourney.tourney.Date }}</td>
                            </tr>{% endfor %}
                    {% elif profile.third_place.count > 0 %}
                        {% for tourney in profile.third_place.all %}
                            <tr>
                                <td>3rd</td>
                                <td>{{ tourney.tourney }}</td>
                                <td>{{ tourney.tourney.Date }}</td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td colspan="3">No Data Available</td>
                        </tr>
                    {% endif %}
                    </tbody>
                </table>
            </div>{% endif %}

        {% if profile.age == 21 %}
            <h3 class="">You old, right?</h3>
            <p>YEAH, 21! SUCK MY DICK! YEAH!</p>
        {% endif %}

        <br/>
    </div>

    {#    <a class="btn btn-primary btn-block" href="{% url 'home' %}">Home</a>#}
{% endblock %}

templates/profiles/view-all.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Players
{% endblock %}
{% block page-title %}
    All Players
{% endblock %}
{% block page-sub-title %}
    You'll probably need to hit that search box.
{% endblock %}
{% block content %}
    <form method="get">
        {% crispy form %}
    </form>
    <hr/>
    <div>
        {% if profile_list %}
            <ul class="list-group">
                {% for profile in profile_list %}
                    <li class="list-group-item">
                        <a href="{% url 'Accounts:view-profile' profile.pk %}" class="btn btn-block"
                           title="{{ profile.tagline }}">{{ profile.user.username }} {% if profile.stalked %}
                            - {{ profile.stalked.count }} follower{{ profile.stalked.count|pluralize }} {% endif %}</a>
                    </li>
                {% endfor %}
            </ul>
            {% if is_paginated %}
                <div class="paginator">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="?{{ search_request }}&page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="page-current">{{ page_obj.number }}/{{ page_obj.has_other_pages }}</span>
                    {% if page_obj.has_next %}
                        <a href="?{{ search_request }}&page={{ page_obj.next_page_number }}">next</a>
                    {% endif %}
                </span>
                </div>
            {% endif %}
        {% else %}
            No one found. Try again.
        {% endif %}
    </div>
{% endblock %}

templates/profiles/view.html
{% extends 'base.html' %}

{% block title %}
    Profile View
{% endblock %}

{% block content %}

    <section class="row mx-auto col-6">
        <div class="col-sm-6">
            <p>
                <img src="{{ profile.avatar.url }}" alt="AVATAR" class="img-thumbnail img-circle-avatar">
            </p>
        </div>
        <div class="col-sm-6">
            <h3>{{ profile.user.username }}</h3>
            <p class="lead">{{ profile.age }} {{ profile.get_gender_display }}</p>
            <div>
                <ul class="list-group">
                    <li class="list-group-item bg-dark">Name: {{ user.get_full_name }}</li>
                    <li class="list-group-item bg-dark">Location: {{ profile.city }}, {{ profile.state }}</li>
                    <li class="list-group-item bg-dark">"{{ profile.tagline }}"</li>
                </ul>
                <br/>
                <h3>Personal Bio</h3>
                <p>{{ profile.bio }}</p>
            </div>
        </div>
    </section>
    <div class="text-center">
        <h3 class="">Latest Scores coming soon!</h3>
        {% if profile.age > 21 %}
            <p>YEAH, 21! SUCK MY DICK! YEAH!</p>
        {% endif %}

        <br/>
    </div>

    {% if profile.user.username == user.username %}

    {% endif %}
    <a class="btn btn-primary btn-block" href="{% url 'home' %}">Home</a>
{% endblock %}