DDR4/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('s/', include('Scores.urls', namespace='Scores')),
    path('l/', include('League.urls', namespace='League')),
    path('a/', include('Accounts.urls', namespace='Accounts')),
    path('accounts/', include([
        path('admin/', admin.site.urls, name="access-panel"),
        path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
        path('logout/', auth_views.LogoutView.as_view(next_page='home'), name='logout'),
    ])),
    path('info/', include([
        path('about', views.about, name='about'),
        path('contact', views.contact, name='contact'),
        path('contribute', views.contribute, name='contribute')
    ])),

    # path('feed/', views.FeedSet.as_view(), name='live-feed'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

League/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from League import views

app_name = "League"
urlpatterns = [
    path('l/', include([
        path('', views.LeagueViewAll.as_view(), name='league-list'),
        path('MakeLeague', views.LeagueCreate.as_view(), name='league-add'),
        path('<int:pk>', views.LeagueView.as_view(), name='league-view'),
        path('<int:pk>/league_entry', views.enter_league, name='league-entry')
    ])),
    path('t/', include([
        path('', views.TrialViewAll.as_view(), name='trial-list'),
        path('<int:pk>', views.TrialView.as_view(), name='trial-view'),
        path('<int:pk>/trial_entry', views.add_trial, name='trial-entry'),
    ])),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

League/models.py
from datetime import datetime, date
from typing import Tuple

from django.contrib.auth.models import User
from django.db import models
from django.db.models.fields.files import ImageFieldFile

from Accounts.models import Profile
from Scores.models import SongChart

DIVISION_CHOICES = [
    ('M', 'Master'),
    ('U', 'Upper Expert'),
    ('L', 'Lower Expert'),
    ('N', 'Novice')
]


class LeagueManager(models.Manager):
    """League manager"""

    @staticmethod
    def enter_league(event, entry, div=None):
        """Enters someone into a League
        :param event: The League in question
        :param entry: The user entered into it
        :param div: The division as an int?
        :return:
        """
        if div is None:
            div = 2
        rel = LeagueEntry.objects.get_or_create(tourney=event, entrants=entry, division=div)
        return rel

    def __str__(self):
        return F"{self.tourney.name} - {self.entrants.rival_code} - {self.division}"


class League(models.Model):
    """Model for the Leagues"""
    name: str = models.CharField(max_length=100)
    organizer: User = models.OneToOneField(User, on_delete=models.CASCADE)
    rules: str = models.TextField(max_length=10000, help_text="Detail all of the rules of your League here.")
    competition_date_start: date = models.DateField(default=datetime.now)
    competition_date_end: date = models.DateField(default=datetime.now)

    @property
    def __str__(self):
        return f"{self.name}, {self.competition_date_start} - {self.competition_date_end}"


class LeagueResult(models.Model):
    """Model for league results display"""
    league: League = models.ForeignKey(League, models.CASCADE)
    winner: Profile = models.ForeignKey(Profile, on_delete=models.DO_NOTHING, related_name='winner')
    second: Profile = models.ForeignKey(Profile, on_delete=models.DO_NOTHING, related_name='second_place')
    third: Profile = models.ForeignKey(Profile, on_delete=models.DO_NOTHING, related_name='third_place')

    @property
    def __str__(self):
        return f"{self.league.name}"


class LeagueEntry(models.Model):
    """Model for league entry results"""
    league: League = models.ForeignKey(League, models.CASCADE)
    entrants: Profile = models.ForeignKey(Profile, on_delete=models.DO_NOTHING, related_name='entrant')
    division: str = models.CharField(choices=DIVISION_CHOICES, max_length=1)

    federation: LeagueManager = LeagueManager()


class TrialManager(models.Manager):
    """Trial management"""

    @staticmethod
    def start_trial(event, dancer):
        """
        For adding a trial.
        :param event: Trial itself.
        :param dancer: The profile of the player taking it on.
        :return:
        """
        rel: Tuple[TrialEntry, bool] = TrialEntry.objects.get_or_create(trial=event, player=dancer)
        return rel


class Trial(models.Model):
    """Model for Trials"""
    title: str = models.CharField(max_length=100)
    deadline: datetime = models.DateTimeField()
    division: str = models.CharField(choices=DIVISION_CHOICES, max_length=1)
    song1: SongChart = models.ForeignKey(SongChart, models.CASCADE, related_name="first_song")
    song2: SongChart = models.ForeignKey(SongChart, models.CASCADE, related_name="second_song")
    song3: SongChart = models.ForeignKey(SongChart, models.CASCADE, related_name="third_song")
    song4: SongChart = models.ForeignKey(SongChart, models.CASCADE, related_name="final_song")
    art: ImageFieldFile = models.ImageField(null=True, blank=True, upload_to='images/trial_art')

    def __str__(self):
        return f"{self.title} - {self.deadline}"

    @property
    def trial_list(self):
        """
        Returns a list name for the trials.
        :return:
        """
        return f"{self.song1.name}, {self.song2.name}, {self.song3.name}, {self.song4.name}"


class TrialEntry(models.Model):
    """Model for trial entry"""
    trial: Trial = models.ForeignKey(Trial, models.CASCADE, related_name="challenge")
    player: Profile = models.ForeignKey(Profile, models.CASCADE, related_name="challenger")

    objects: TrialManager = TrialManager()

League/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic

from League.models import League, LeagueEntry, LeagueManager, TrialManager, TrialEntry, Trial


class LeagueViewAll(generic.ListView):
    model = League
    queryset = League.objects.all()
    template_name = "leagues/league-view-all.html"


class LeagueView(generic.DetailView):
    model = League
    queryset = League.objects.all()
    template_name = "leagues/league-view.html"


class LeagueCreate(generic.CreateView):
    model = League
    template_name = "leagues/league-submit.html"
    success_url = reverse_lazy("League:league-list")
    fields = ('name', 'organizer', 'mix', 'rules', 'competition_date_start', 'competition_date_end')

    def form_valid(self, form):
        """
        Checks validation of the form
        :param form:
        :return:
        """
        # form.instance.player = self.request.user.profile
        return super().form_valid(form)


class TrialViewAll(generic.ListView):
    model = Trial
    queryset = Trial.objects.all()
    template_name = "leagues/trial-view-all.html"


class TrialView(generic.DetailView):
    model = Trial
    queryset = Trial.objects.all()
    template_name = "leagues/trial-view.html"


class TrialCreate(generic.CreateView):
    model = Trial
    success_url = reverse_lazy("League:trial-view")


@login_required
def enter_league(request, pk):
    """For adding someone to a League
    :param request: User stats
    :param pk: PK for league
    :return:
    """
    if request.method == "POST":
        event = League.objects.get(pk=pk)
        entry = request.user.profile
        try:
            LeagueManager.enter_League(event=event, entry=entry)
        except LeagueEntry.DoesNotExist:
            return False
        else:
            messages.error(request, "ERROR: Something went wrong.")
            return redirect('League:league-view', pk)

    messages.success(request, "Success! You're in.")
    return render(request, "leagues/league-view-all.html")


@login_required
def add_trial(request, pk):
    """
    For adding a trial to your profile
    :param request: User stats
    :param pk: PK for the trial
    """
    if request.method == "POST":
        event = Trial.objects.get(pk=pk)
        dancer = request.user.profile
        try:
            TrialManager.start_trial(event=event, dancer=dancer)
        except TrialEntry.DoesNotExist:
            return False
        else:
            messages.error(request, "ERROR: Something went wrong.")
            return redirect('League:trial-view', pk)

    messages.success(request, "Success! You're in.")
    return render(request, "leagues/trial-view-all.html")

templates/leagues/league-submit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    League Submission
{% endblock %}
{% block page-title %}
    League Submission
{% endblock %}
{% block page-sub-title %}
    Time to make a new league.
{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data" action="{% url "League:league-add" %}">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-block btn-success">Create League</button>
    </form>
{% endblock %}

templates/leagues/league-view-all.html
{% extends 'base.html' %}

{% block title %}
    Leagues
{% endblock %}
{% block page-title %}
    League Events
{% endblock %}
{% block page-sub-title %}
    Check for an event in your area!
{% endblock %}
{% block content %}
    {% if league_list.count > 0 %}
        <ul class="list-group">
            {% for league in league_list %}
                <li class="list-group-item bg-dark"><a
                        href="{% url 'League:league-view' league.pk %}"
                        class="btn btn-block btn-outline-light">{{ league.name }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <div class="text-center">
            <h4>No events found.</h4></div>
    {% endif %}

    {% if user.is_staff %}
        <hr>
        <a href="{% url 'League:league-add' %}" class="btn btn-primary btn-block">Make a new league</a>
    {% endif %}

{% endblock %}

templates/leagues/league-view.html
{% extends 'base.html' %}

{% block title %}
    League Detail - {{ league.name }}
{% endblock %}
{% block page-title %}
    League Detail
{% endblock %}
{% block page-sub-title %}
    {{ league.name }}
{% endblock %}
{% block content %}
    <table class="table table-bordered table-dark">
        <thead class="thead-light">
        <tr>
            <th colspan="2">
                League Data
            </th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td><b>Organizer</b></td>
            <td>{{ league.organizer.get_full_name }} [{{ league.organizer.username }}]</td>
        </tr>
        <tr>
            <td><b>Location</b></td>
            <td>{{ league.mix }}</td>
        </tr>
        <tr>
            <td><b>Length</b></td>
            <td>{{ league.competition_date_start }} - {{ league.competition_date_end }}</td>
        </tr>
        <tr>
            <td><b>Rules</b></td>
            <td>{{ league.rules }}</td>
        </tr>
        <tr>
            <td><b>Entrants</b></td>
            <td>{% if league.leagueentry_set.count > 0 %}
                {% for foo in league.leagueentry_set.all %}
                    {{ foo.entrants.user.username }}<br/>
                {% endfor %}
            {% else %}
                None
            {% endif %}</td>
        </tr>
        </tbody>
    </table>

    {% if user.is_authenticated %}
        {% if league.organizer != user %}
            {% if user not in league.leagueentry_set.get.all %}
                <form method="post" action="{% url 'League:league-entry' league.pk %}">
                    {% csrf_token %}
                    <h5>Enter this league?</h5>
                    <div class="btn btn-group">
                        <button class="btn btn-block btn-primary">Join League</button>
                    </div>
                </form>
            {% endif %}
        {% endif %}
    {% endif %}
{% endblock %}

templates/leagues/trial-view-all.html
{% extends 'base.html' %}

{% block title %}
    Trials!
{% endblock %}
{% block page-title %}
    Trials
{% endblock %}
{% block page-sub-title %}
    We thought you could use the extra challenge
{% endblock %}
{% block content %}
    {% if trial_list %}
        <table class="table table-striped table-dark table-bordered text-center">
            <thead class="thead-light">
            <th>Name</th>
            <th>Division</th>
            <th>Deadline</th>
            <th colspan="4">Songs</th>
            </thead>
            <tbody class="tbody-light">
            {% for trial in trial_list %}
                <td><a href="{% url 'League:trial-view' pk=trial.pk %}">{{ trial.title }}</a></td>
                <td>{{ trial.division }}</td>
                <td>{{ trial.deadline|date }}</td>
                <td>{{ trial.song1 }}</td>
                <td>{{ trial.song2 }}</td>
                <td>{{ trial.song3 }}</td>
                <td>{{ trial.song4 }}</td>
            {% endfor %}
            </tbody>
        </table>{% else %}
        <p class="text-center">No trials loaded.</p>

    {% endif %}
{% endblock %}

templates/leagues/trial-view.html
{% extends 'base.html' %}

{% block title %}
    Trial View - {{ trial.title }}
{% endblock %}
{% block page-title %}
    Trials
{% endblock %}
{% block page-sub-title %}
    {{ trial.title }}
{% endblock %}
{% block content %}
    <table class="table table-lg table-bordered bg-dark text-center">
        <thead class="thead-light">
        <tr>
            <th colspan="4">
                <h3>{{ trial.title }}</h3>
            </th>
        </tr>
        </thead>
        <tbody class="text-light">
        <tr>
            <td>{{ trial.song1.name }}</td>
            <td>{{ trial.song2.name }}</td>
            <td>{{ trial.song3.name }}</td>
            <td>{{ trial.song4.name }}</td>
        </tr>
        <tr>
            <td colspan="4">Deadline for scores: {{ trial.deadline|date }}</td>
        </tr>
        </tbody>
    </table>
    <form action="{% url 'League:trial-entry' trial.pk %}" method="post">
        {% csrf_token %}
        <button class="btn btn-block btn-primary">Accept this trial?</button>
    </form>
{% endblock %}